name: Deploy to Render

# Chạy khi push vào nhánh main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Cài dependencies (bao gồm dev để build Nest)
      - name: Install dependencies
        run: npm install --include=dev

      # 4. Build project (dùng npx để chắc chắn tìm thấy Nest CLI)
      - name: Build project
        run: npm run build

      # 5. Deploy lên Render
      - name: Deploy to Render
        uses: render-examples/deploy@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
